################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_attributes_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_attributes_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_create.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_default_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_default_get_copy.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_default_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_delete.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_entry_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_entry_write.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_first_entry_find.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_first_full_entry_find.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_free_search.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_information_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_clear.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_get_copy.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_restore.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_long_name_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_long_name_get_extended.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_name_extract.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_name_test.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_next_entry_find.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_next_full_entry_find.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_rename.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_search.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_short_name_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_directory_short_name_get_extended.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_add_FAT_log.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_add_bitmap_log.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_add_checksum_log.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_add_dir_log.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_apply_logs.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_calculate_checksum.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_cleanup_FAT_chain.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_create_log_file.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_enable.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_read_FAT.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_read_directory_sector.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_read_log_file.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_recover.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_reset_log_file.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_set_FAT_chain.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_transaction_end.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_transaction_fail.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_transaction_start.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_write_log_file.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_allocate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_attributes_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_attributes_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_best_effort_allocate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_close.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_create.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_date_time_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_delete.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_allocate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_best_effort_allocate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_relative_seek.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_seek.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_truncate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_truncate_release.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_open.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_relative_seek.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_rename.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_seek.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_truncate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_truncate_release.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_write.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_file_write_notify_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_abort.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_boot_info_extract.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_cache_invalidate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_check.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_check_FAT_chain_check.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_check_lost_cluster_check.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_close.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_close_notify_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_extended_space_available.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_flush.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_format.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_open.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_open_notify_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_space_available.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_volume_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_volume_get_extended.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_volume_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_media_write.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_ram_driver.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_system_date_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_system_date_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_system_initialize.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_system_time_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_system_time_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_system_timer_entry.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_trace_event_insert.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_trace_event_update.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_trace_object_register.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_trace_object_unregister.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_create.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_entry_change.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_entry_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_rename.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_search.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_file_create.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_file_rename.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_length_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_length_get_extended.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_name_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_name_get_extended.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_short_name_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_short_name_get_extended.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_16_unsigned_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_16_unsigned_write.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_32_unsigned_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_32_unsigned_write.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_64_unsigned_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_64_unsigned_write.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_entry_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_entry_write.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_flush.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_map_flush.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_sector_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_absolute_path_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_logical_sector_cache_entry_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_logical_sector_flush.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_logical_sector_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_logical_sector_write.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_memory_copy.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_memory_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_string_length_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fx_utility_token_length_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_attributes_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_attributes_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_create.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_default_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_default_get_copy.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_default_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_delete.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_first_entry_find.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_first_full_entry_find.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_information_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_clear.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_get_copy.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_restore.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_long_name_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_long_name_get_extended.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_name_test.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_next_entry_find.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_next_full_entry_find.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_rename.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_short_name_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_short_name_get_extended.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_fault_tolerant_enable.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_allocate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_attributes_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_attributes_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_best_effort_allocate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_close.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_create.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_date_time_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_delete.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_allocate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_best_effort_allocate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_relative_seek.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_seek.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_truncate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_truncate_release.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_open.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_relative_seek.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_rename.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_seek.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_truncate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_truncate_release.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_write.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_file_write_notify_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_abort.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_cache_invalidate.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_check.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_close.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_close_notify_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_extended_space_available.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_flush.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_format.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_open.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_open_notify_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_read.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_space_available.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_volume_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_volume_get_extended.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_volume_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_media_write.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_system_date_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_system_date_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_system_time_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_system_time_set.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_directory_create.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_directory_rename.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_file_create.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_file_rename.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_name_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_name_get_extended.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_short_name_get.c \
../synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_short_name_get_extended.c 

C_DEPS += \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_attributes_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_attributes_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_create.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_default_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_default_get_copy.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_default_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_delete.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_entry_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_entry_write.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_first_entry_find.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_first_full_entry_find.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_free_search.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_information_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_clear.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_get_copy.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_restore.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_long_name_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_long_name_get_extended.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_name_extract.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_name_test.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_next_entry_find.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_next_full_entry_find.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_rename.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_search.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_short_name_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_short_name_get_extended.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_add_FAT_log.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_add_bitmap_log.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_add_checksum_log.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_add_dir_log.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_apply_logs.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_calculate_checksum.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_cleanup_FAT_chain.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_create_log_file.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_enable.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_read_FAT.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_read_directory_sector.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_read_log_file.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_recover.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_reset_log_file.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_set_FAT_chain.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_transaction_end.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_transaction_fail.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_transaction_start.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_write_log_file.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_allocate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_attributes_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_attributes_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_best_effort_allocate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_close.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_create.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_date_time_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_delete.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_allocate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_best_effort_allocate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_relative_seek.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_seek.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_truncate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_truncate_release.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_open.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_relative_seek.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_rename.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_seek.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_truncate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_truncate_release.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_write.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_write_notify_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_abort.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_boot_info_extract.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_cache_invalidate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_check.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_check_FAT_chain_check.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_check_lost_cluster_check.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_close.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_close_notify_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_extended_space_available.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_flush.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_format.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_open.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_open_notify_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_space_available.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_volume_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_volume_get_extended.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_volume_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_write.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_ram_driver.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_system_date_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_system_date_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_system_initialize.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_system_time_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_system_time_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_system_timer_entry.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_trace_event_insert.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_trace_event_update.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_trace_object_register.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_trace_object_unregister.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_create.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_entry_change.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_entry_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_rename.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_search.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_file_create.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_file_rename.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_length_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_length_get_extended.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_name_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_name_get_extended.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_short_name_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_short_name_get_extended.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_16_unsigned_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_16_unsigned_write.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_32_unsigned_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_32_unsigned_write.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_64_unsigned_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_64_unsigned_write.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_entry_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_entry_write.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_flush.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_map_flush.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_sector_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_absolute_path_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_logical_sector_cache_entry_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_logical_sector_flush.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_logical_sector_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_logical_sector_write.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_memory_copy.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_memory_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_string_length_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_token_length_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_attributes_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_attributes_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_create.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_default_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_default_get_copy.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_default_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_delete.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_first_entry_find.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_first_full_entry_find.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_information_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_clear.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_get_copy.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_restore.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_long_name_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_long_name_get_extended.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_name_test.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_next_entry_find.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_next_full_entry_find.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_rename.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_short_name_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_short_name_get_extended.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_fault_tolerant_enable.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_allocate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_attributes_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_attributes_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_best_effort_allocate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_close.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_create.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_date_time_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_delete.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_allocate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_best_effort_allocate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_relative_seek.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_seek.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_truncate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_truncate_release.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_open.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_relative_seek.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_rename.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_seek.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_truncate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_truncate_release.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_write.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_write_notify_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_abort.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_cache_invalidate.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_check.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_close.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_close_notify_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_extended_space_available.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_flush.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_format.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_open.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_open_notify_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_read.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_space_available.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_volume_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_volume_get_extended.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_volume_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_write.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_system_date_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_system_date_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_system_time_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_system_time_set.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_directory_create.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_directory_rename.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_file_create.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_file_rename.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_name_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_name_get_extended.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_short_name_get.d \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_short_name_get_extended.d 

OBJS += \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_attributes_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_attributes_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_create.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_default_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_default_get_copy.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_default_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_delete.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_entry_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_entry_write.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_first_entry_find.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_first_full_entry_find.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_free_search.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_information_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_clear.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_get_copy.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_restore.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_local_path_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_long_name_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_long_name_get_extended.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_name_extract.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_name_test.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_next_entry_find.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_next_full_entry_find.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_rename.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_search.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_short_name_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_directory_short_name_get_extended.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_add_FAT_log.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_add_bitmap_log.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_add_checksum_log.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_add_dir_log.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_apply_logs.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_calculate_checksum.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_cleanup_FAT_chain.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_create_log_file.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_enable.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_read_FAT.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_read_directory_sector.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_read_log_file.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_recover.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_reset_log_file.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_set_FAT_chain.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_transaction_end.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_transaction_fail.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_transaction_start.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_fault_tolerant_write_log_file.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_allocate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_attributes_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_attributes_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_best_effort_allocate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_close.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_create.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_date_time_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_delete.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_allocate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_best_effort_allocate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_relative_seek.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_seek.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_truncate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_extended_truncate_release.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_open.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_relative_seek.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_rename.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_seek.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_truncate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_truncate_release.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_write.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_file_write_notify_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_abort.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_boot_info_extract.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_cache_invalidate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_check.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_check_FAT_chain_check.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_check_lost_cluster_check.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_close.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_close_notify_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_extended_space_available.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_flush.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_format.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_open.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_open_notify_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_space_available.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_volume_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_volume_get_extended.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_volume_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_media_write.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_ram_driver.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_system_date_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_system_date_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_system_initialize.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_system_time_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_system_time_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_system_timer_entry.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_trace_event_insert.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_trace_event_update.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_trace_object_register.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_trace_object_unregister.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_create.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_entry_change.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_entry_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_rename.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_directory_search.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_file_create.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_file_rename.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_length_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_length_get_extended.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_name_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_name_get_extended.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_short_name_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_unicode_short_name_get_extended.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_16_unsigned_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_16_unsigned_write.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_32_unsigned_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_32_unsigned_write.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_64_unsigned_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_64_unsigned_write.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_entry_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_entry_write.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_flush.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_map_flush.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_FAT_sector_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_absolute_path_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_logical_sector_cache_entry_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_logical_sector_flush.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_logical_sector_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_logical_sector_write.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_memory_copy.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_memory_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_string_length_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fx_utility_token_length_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_attributes_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_attributes_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_create.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_default_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_default_get_copy.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_default_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_delete.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_first_entry_find.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_first_full_entry_find.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_information_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_clear.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_get_copy.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_restore.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_local_path_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_long_name_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_long_name_get_extended.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_name_test.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_next_entry_find.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_next_full_entry_find.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_rename.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_short_name_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_directory_short_name_get_extended.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_fault_tolerant_enable.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_allocate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_attributes_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_attributes_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_best_effort_allocate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_close.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_create.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_date_time_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_delete.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_allocate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_best_effort_allocate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_relative_seek.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_seek.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_truncate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_extended_truncate_release.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_open.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_relative_seek.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_rename.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_seek.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_truncate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_truncate_release.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_write.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_file_write_notify_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_abort.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_cache_invalidate.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_check.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_close.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_close_notify_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_extended_space_available.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_flush.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_format.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_open.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_open_notify_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_read.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_space_available.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_volume_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_volume_get_extended.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_volume_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_media_write.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_system_date_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_system_date_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_system_time_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_system_time_set.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_directory_create.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_directory_rename.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_file_create.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_file_rename.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_name_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_name_get_extended.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_short_name_get.o \
./synergy/ssp/src/framework/el/fx/fx_src/fxe_unicode_short_name_get_extended.o 

SREC += \
IoTRamoRenesas.srec 

MAP += \
IoTRamoRenesas.map 


# Each subdirectory must supply rules for building sources it contributes
synergy/ssp/src/framework/el/fx/fx_src/%.o: ../synergy/ssp/src/framework/el/fx/fx_src/%.c
	$(file > $@.in,-mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O2 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-strict-aliasing -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -g -D_RENESAS_SYNERGY_ -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy_cfg/ssp_cfg/bsp" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy_cfg/ssp_cfg/driver" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/bsp" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/bsp/cmsis/Include" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/driver/api" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/driver/instances" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/src" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/src/synergy_gen" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy_cfg/ssp_cfg/framework" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/framework/api" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/framework/instances" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/framework/el/nxd" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/nxd" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/framework/el/nxd_application_layer" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/framework/tes" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy_cfg/ssp_cfg/framework/el" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/framework/el" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/tx/tx_src" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/fx/fx_src" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/fx/fx_src/filex_exFAT" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/nx_md5" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/tx" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/sf_el_nx/phy" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/nxd/nxd_src" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" -x c "$<")
	@echo Building file: $< && arm-none-eabi-gcc @"$@.in"

