################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../synergy/ssp/src/framework/el/tx/tx_src/tx_block_allocate.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_cleanup.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_initialize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_performance_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_performance_system_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_prioritize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_block_release.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_byte_allocate.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_cleanup.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_initialize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_performance_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_performance_system_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_prioritize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_search.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_byte_release.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_cleanup.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_initialize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_performance_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_performance_system_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_set.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_set_notify.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_initialize_high_level.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_initialize_kernel_enter.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_initialize_kernel_setup.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_isr_end.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_isr_start.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_misra.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_cleanup.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_initialize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_performance_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_performance_system_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_prioritize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_priority_change.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_put.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_cleanup.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_flush.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_front_send.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_initialize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_performance_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_performance_system_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_prioritize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_receive.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_send.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_queue_send_notify.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_ceiling_put.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_cleanup.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_initialize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_performance_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_performance_system_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_prioritize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_put.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_put_notify.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_entry_exit_notify.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_identify.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_initialize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_performance_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_performance_system_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_preemption_change.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_priority_change.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_relinquish.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_reset.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_resume.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_shell_entry.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_sleep.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_stack_analyze.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_stack_error_handler.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_stack_error_notify.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_suspend.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_system_preempt_check.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_system_resume.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_system_suspend.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_terminate.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_time_slice.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_time_slice_change.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_timeout.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_thread_wait_abort.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_time_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_time_set.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_activate.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_change.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_deactivate.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_expiration_process.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_initialize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_performance_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_performance_system_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_system_activate.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_system_deactivate.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_timer_thread_entry.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_trace_buffer_full_notify.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_trace_disable.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_trace_enable.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_trace_event_filter.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_trace_event_unfilter.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_trace_initialize.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_trace_interrupt_control.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_trace_isr_enter_insert.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_trace_isr_exit_insert.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_trace_object_register.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_trace_object_unregister.c \
../synergy/ssp/src/framework/el/tx/tx_src/tx_trace_user_event_insert.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_block_allocate.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_block_pool_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_block_pool_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_block_pool_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_block_pool_prioritize.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_block_release.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_byte_allocate.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_byte_pool_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_byte_pool_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_byte_pool_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_byte_pool_prioritize.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_byte_release.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_set.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_set_notify.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_prioritize.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_put.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_queue_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_queue_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_queue_flush.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_queue_front_send.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_queue_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_queue_prioritize.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_queue_receive.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_queue_send.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_queue_send_notify.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_ceiling_put.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_prioritize.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_put.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_put_notify.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_entry_exit_notify.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_info_get.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_preemption_change.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_priority_change.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_relinquish.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_reset.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_resume.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_suspend.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_terminate.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_time_slice_change.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_thread_wait_abort.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_timer_activate.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_timer_change.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_timer_create.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_timer_deactivate.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_timer_delete.c \
../synergy/ssp/src/framework/el/tx/tx_src/txe_timer_info_get.c 

C_DEPS += \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_allocate.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_cleanup.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_initialize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_performance_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_performance_system_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_prioritize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_release.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_allocate.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_cleanup.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_initialize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_performance_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_performance_system_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_prioritize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_search.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_release.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_cleanup.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_initialize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_performance_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_performance_system_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_set.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_set_notify.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_initialize_high_level.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_initialize_kernel_enter.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_initialize_kernel_setup.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_isr_end.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_isr_start.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_misra.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_cleanup.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_initialize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_performance_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_performance_system_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_prioritize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_priority_change.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_put.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_cleanup.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_flush.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_front_send.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_initialize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_performance_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_performance_system_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_prioritize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_receive.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_send.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_send_notify.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_ceiling_put.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_cleanup.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_initialize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_performance_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_performance_system_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_prioritize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_put.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_put_notify.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_entry_exit_notify.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_identify.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_initialize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_performance_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_performance_system_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_preemption_change.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_priority_change.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_relinquish.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_reset.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_resume.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_shell_entry.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_sleep.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_stack_analyze.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_stack_error_handler.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_stack_error_notify.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_suspend.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_system_preempt_check.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_system_resume.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_system_suspend.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_terminate.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_time_slice.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_time_slice_change.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_timeout.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_wait_abort.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_time_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_time_set.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_activate.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_change.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_deactivate.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_expiration_process.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_initialize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_performance_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_performance_system_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_system_activate.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_system_deactivate.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_thread_entry.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_buffer_full_notify.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_disable.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_enable.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_event_filter.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_event_unfilter.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_initialize.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_interrupt_control.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_isr_enter_insert.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_isr_exit_insert.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_object_register.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_object_unregister.d \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_user_event_insert.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_block_allocate.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_block_pool_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_block_pool_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_block_pool_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_block_pool_prioritize.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_block_release.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_byte_allocate.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_byte_pool_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_byte_pool_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_byte_pool_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_byte_pool_prioritize.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_byte_release.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_set.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_set_notify.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_prioritize.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_put.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_flush.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_front_send.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_prioritize.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_receive.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_send.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_send_notify.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_ceiling_put.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_prioritize.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_put.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_put_notify.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_entry_exit_notify.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_info_get.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_preemption_change.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_priority_change.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_relinquish.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_reset.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_resume.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_suspend.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_terminate.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_time_slice_change.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_wait_abort.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_timer_activate.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_timer_change.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_timer_create.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_timer_deactivate.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_timer_delete.d \
./synergy/ssp/src/framework/el/tx/tx_src/txe_timer_info_get.d 

OBJS += \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_allocate.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_cleanup.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_initialize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_performance_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_performance_system_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_pool_prioritize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_block_release.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_allocate.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_cleanup.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_initialize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_performance_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_performance_system_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_prioritize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_pool_search.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_byte_release.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_cleanup.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_initialize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_performance_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_performance_system_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_set.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_event_flags_set_notify.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_initialize_high_level.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_initialize_kernel_enter.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_initialize_kernel_setup.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_isr_end.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_isr_start.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_misra.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_cleanup.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_initialize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_performance_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_performance_system_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_prioritize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_priority_change.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_mutex_put.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_cleanup.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_flush.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_front_send.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_initialize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_performance_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_performance_system_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_prioritize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_receive.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_send.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_queue_send_notify.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_ceiling_put.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_cleanup.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_initialize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_performance_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_performance_system_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_prioritize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_put.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_semaphore_put_notify.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_entry_exit_notify.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_identify.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_initialize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_performance_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_performance_system_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_preemption_change.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_priority_change.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_relinquish.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_reset.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_resume.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_shell_entry.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_sleep.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_stack_analyze.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_stack_error_handler.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_stack_error_notify.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_suspend.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_system_preempt_check.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_system_resume.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_system_suspend.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_terminate.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_time_slice.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_time_slice_change.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_timeout.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_thread_wait_abort.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_time_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_time_set.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_activate.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_change.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_deactivate.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_expiration_process.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_initialize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_performance_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_performance_system_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_system_activate.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_system_deactivate.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_timer_thread_entry.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_buffer_full_notify.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_disable.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_enable.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_event_filter.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_event_unfilter.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_initialize.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_interrupt_control.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_isr_enter_insert.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_isr_exit_insert.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_object_register.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_object_unregister.o \
./synergy/ssp/src/framework/el/tx/tx_src/tx_trace_user_event_insert.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_block_allocate.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_block_pool_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_block_pool_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_block_pool_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_block_pool_prioritize.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_block_release.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_byte_allocate.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_byte_pool_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_byte_pool_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_byte_pool_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_byte_pool_prioritize.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_byte_release.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_set.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_event_flags_set_notify.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_prioritize.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_mutex_put.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_flush.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_front_send.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_prioritize.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_receive.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_send.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_queue_send_notify.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_ceiling_put.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_prioritize.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_put.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_semaphore_put_notify.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_entry_exit_notify.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_info_get.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_preemption_change.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_priority_change.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_relinquish.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_reset.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_resume.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_suspend.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_terminate.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_time_slice_change.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_thread_wait_abort.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_timer_activate.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_timer_change.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_timer_create.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_timer_deactivate.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_timer_delete.o \
./synergy/ssp/src/framework/el/tx/tx_src/txe_timer_info_get.o 

SREC += \
IoTRamoRenesas.srec 

MAP += \
IoTRamoRenesas.map 


# Each subdirectory must supply rules for building sources it contributes
synergy/ssp/src/framework/el/tx/tx_src/%.o: ../synergy/ssp/src/framework/el/tx/tx_src/%.c
	$(file > $@.in,-mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O2 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-strict-aliasing -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -g -D_RENESAS_SYNERGY_ -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy_cfg/ssp_cfg/bsp" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy_cfg/ssp_cfg/driver" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/bsp" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/bsp/cmsis/Include" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/driver/api" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/driver/instances" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/src" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/src/synergy_gen" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy_cfg/ssp_cfg/framework" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/framework/api" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/framework/instances" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/framework/el/nxd" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/nxd" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/framework/el/nxd_application_layer" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/framework/tes" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy_cfg/ssp_cfg/framework/el" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/inc/framework/el" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/tx/tx_src" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/fx/fx_src" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/fx/fx_src/filex_exFAT" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/nx_md5" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/tx" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/sf_el_nx/phy" -I"C:/Users/CS/Documents/IoT_Ramo_Renesas/synergy/ssp/src/framework/el/nxd/nxd_src" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" -x c "$<")
	@echo Building file: $< && arm-none-eabi-gcc @"$@.in"

